import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles(() => ({
  program_highlights_main: {
    width: "100vw",
  },
  programmain: {
    // height: "100vh",
    padding: "60px 60px 5px 60px",
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "20px",
    alignItems: "center",
    justifyContent: "center",
    gridAutoRows: "minmax(150px, auto)",
    width: "100%",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  programhead: {
    textAlign:"center",
    fontSize: "1.5rem",
    fontWeight: "bold",
    padding: "20px 70px",
  },
  highlights1: {
    backgroundColor: "#D8F6FF",
    height: "200px",
    width: "275px",
    borderRadius: "20px",
    padding: "80px 50px",
    textAlign: "center",
    fontSize: "1.5rem",
    position: "relative",
    marginBottom: "50px",
  },
  highlights2: {
    backgroundColor: "#F3FCFF",
    height: "200px",
    width: "275px",
    borderRadius: "20px",
    padding: "80px 50px",
    textAlign: "center",
    fontSize: "1.5rem",
    position: "relative",
    marginBottom: "50px",
  },
  videocall: {
    height: "80px",
    width: "80px",
    background: "linear-gradient(to bottom, #1455FE, #41FCFF)",
    padding: "15px 20px",
    borderRadius: "50px",
    objectFit: "contain",
    objectPosition: "center",
    position: "absolute",
    top: "-40px",
    left: "95px",
  },
  videologo: {
    height: "40px",
    width: "40px",
    objectFit: "contain",
  },
}));
